### ISSUE TITLE
Blind-files - .czi

### ISSUE THREAD

**Issue by JDeeDyer** [Macklin-Lab/imagej-microscopy-scripts#1]
Hi Nick,

I'm a PhD from the University of Exeter (UK), firstly, thank you for all you've done on here. I'm really keen to get the blind-files script working for me. For various (annoying!) reasons I need to perform part of my analysis in Zen blue, it would be amazing if I could blind the .czi files directly rather than converting to .tif first.  Would it be possible for you to add the ability to convert .czi files as you discuss on the README?

Best wishes,
Josh

**Comment by nkicg6** [comment]
Hi Josh,
I am glad you find these useful! I updated blind-files to process czi's and a few other formats as well as adding some logging messages (here https://github.com/Macklin-Lab/imagej-microscopy-scripts/commit/a20445f8120c8263b1aedafb410f1f6b3fc1c823 ). I am uploading them to the Fiji update site now and they should be available after restarting and updating Fiji shortly. Let me know if you have any other problems!  
Nick

**Comment by JDeeDyer** [comment]
Amazing, thank you so much Nick.

Josh
